// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafePath.EntityFrameworkCore.FastStorage;

#nullable disable

namespace SafePath.Migrations.SqliteDb
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("SafePath.Entities.FastStorage.MapElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("EdgeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItineroMappingError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<long?>("OSMNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("VertexId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Lat", "Lng");

                    b.ToTable("MapElement", (string)null);
                });

            modelBuilder.Entity("SafePath.Entities.FastStorage.SafetyScoreElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("EdgeId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EdgeId")
                        .IsUnique();

                    b.ToTable("SafetyScoreElement", (string)null);
                });

            modelBuilder.Entity("SafePath.Entities.FastStorage.SafetyScoreElementMapElement", b =>
                {
                    b.Property<int>("SafetyScoreElementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SafetyScoreElementId", "MapElementId");

                    b.HasIndex("MapElementId");

                    b.ToTable("SafetyScoreElementMapElement");
                });

            modelBuilder.Entity("SafePath.Entities.FastStorage.SafetyScoreElementMapElement", b =>
                {
                    b.HasOne("SafePath.Entities.FastStorage.MapElement", "MapElement")
                        .WithMany()
                        .HasForeignKey("MapElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafePath.Entities.FastStorage.SafetyScoreElement", "SafetyScoreElement")
                        .WithMany()
                        .HasForeignKey("SafetyScoreElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapElement");

                    b.Navigation("SafetyScoreElement");
                });
#pragma warning restore 612, 618
        }
    }
}
